### ISSUE TITLE
Please create a formula for Homebrew.

### ISSUE THREAD

**Issue by paulyhedral** [reconquest/tubekit#1]

**Comment by kovetskiy** [comment]
Hey! Check this out: https://github.com/reconquest/tubekit#macos

Please let me know if it helped you

**Comment by nesl247** [comment]
There is an issue in the installation instructions. It needs to be `brew install reconquest/tubekit/tubekit` or the `tap` name needs to be changed.

**Comment by kovetskiy** [comment]
Closed by #6
