### ISSUE TITLE
kubectl binary path

### ISSUE THREAD

**Issue by e1senh0rn** [reconquest/tubekit#4]
In macOS (using homebrew) kubectl location is `/usr/local/bin/kubectl`. It might as well be customized to reside within home directory, etc.

There is env variable `TUBEKIT_KUBECTL` to explicitly provide path to kubectl.
This might be useful if targeting particular version of kubectl, but I think in general case kubectl from PATH should be used.

I'm not quite familiar with Go and k8s SDK, but suppose something similar to this could be implemented:
https://github.com/kubernetes/kops/blob/af4df08b694e2a1f8814a7b3649060477be67c86/upup/pkg/kutil/kubectl.go#L116

PS: also `tubectl` does not return an error if `kubectl` is not found, it simply does `exit(0)`. I would expect it to error hard in this case.

**Comment by kovetskiy** [comment]
Hi, yes it definitely makes much more sense than just TUBEKIT_KUBECTL. I've added it, could you please check the latest master version (not published as a release yet)?

**Comment by e1senh0rn** [comment]
Many thanks! It works as expected.
