### ISSUE TITLE
tubectl command line arguments

### ISSUE THREAD

**Issue by e1senh0rn** [reconquest/tubekit#5]
`tubectl` is a thin wrapper on top of `kubectl`, however it should handle at least some command line options on its own.
Currently there is no way to check tubectl version. This would be quite useful to add as an extra test in #1.

**Comment by kovetskiy** [comment]
Hi! Thanks for the suggestion, tubectl definitely missed it. I've added several flags:

https://github.com/reconquest/tubekit#custom-flags
