### ISSUE TITLE
tubectl with --kubeconfig with +namespace throws error

### ISSUE THREAD

**Issue by chngtrn** [reconquest/tubekit#9]
When using tubectl with --kubeconfig flag and +namesapce, it throws error below:
```
$ tubectl --kubeconfig ~/.kube/cluster2 +sys get pod
The connection to the server localhost:6443 was refused - did you specify the right host or port?
2019/06/05 15:34:43 unable to retrieve list of available namespaces
└─ tubectl command failed
   ├─ exit status 1
   └─ cmdline: ["/usr/local/bin/kubectl" "get" "namespaces" "-o" "json"]
```

It works fine using the -n 
```
$ tubectl --kubeconfig ~/.kube/cluster2 -n kube-system get pod
NAME                                                READY   STATUS    RESTARTS   AGE
coredns-78fcdf6894-7c6s8                            1/1     Running   3          299d
...
tiller-deploy-784fb6dbf-q4tjh                       1/1     Running   2          299d
```

**Comment by kovetskiy** [comment]
Hi, 

Couldn't it be related to the fact that you specified different configuration files for these commands?

**Comment by chngtrn** [comment]
Sorry I mean to update the second command to use the same config. Using the same configuration file cause the issue. Please give it a try?

**Comment by kovetskiy** [comment]
It should be fixed now, please check.

**Comment by chngtrn** [comment]
Thank you for the quick fix.

**Comment by kovetskiy** [comment]
Thanks for the confirmation, here is the release: https://github.com/reconquest/tubekit/releases/tag/v4

**Comment by chngtrn** [comment]
Great. Thanks a lot. Great project.
